const popups = document.querySelector('.popup');
const popupsArray = Array.from(document.querySelectorAll('.popup'));
const popupEditProfile = document.querySelector('#profile-popup');
const profileEditButton = document.querySelector('.profile__edit-button');
const profileUserName = document.querySelector('.profile__user-name');
const profileUserStatus = document.querySelector('.profile__user-status');
const profileNameInput = document.querySelector('input[name="username"]');
const profileStatusInput = document.querySelector('input[name="userstatus"]');
const popupCardsAdd = document.querySelector('#cards-popup');
const profileAddButton = document.querySelector('.profile__add-button');
const cardsTitleInput = document.querySelector('input[name="cardTitle"]');
const cardsLinkInput = document.querySelector('input[name="cardLink"]');
const cardContainer = document.querySelector('.elements');
const cardTemplate = document.querySelector('#elementTemplate').content
const popupImage = document.querySelector('#image-popup');
const imageCaption = document.querySelector('.popup__image-caption');
const imagePhoto = document.querySelector('.popup__image');
